title: My Github Lab
description: Learning how to use Git with some advanced capabilities
template:
  repo: my-github-lab-template
  name: my-github-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
